In [6]:
import json
import math
import pandas as pd
import numpy as np
from shapely.geometry import shape, Point
import gamspy as gp

# ----------------------------------------------------
# 1. Load Data & Geometries
# ----------------------------------------------------
# Load district population
df_pop = pd.read_excel(f"Data\جمعیت مناطق-1405-06-25.xlsx")
pop_dict = {
    1: 80807, 2: 76733, 3: 111013, 4: 147139, 5: 132984,
    6: 112896, 7: 206588, 8: 243563, 9: 78271, 10: 200702,
    11: 58334, 12: 155413, 13: 164413, 14: 160354, 15: 138247
}

# Parse 15 district polygons and calculate centroids
with open(r"Data\isfahan_raw.geojson", "r", encoding="utf-8") as f:
    geojson_data = json.load(f)

persian_to_eng = {
    '۱': 1, '۲': 2, '۳': 3, '۴': 4, '۵': 5, '۶': 6, '۷': 7, '۸': 8,
    '۹': 9, '۱۰': 10, '۱۱': 11, '۱۲': 12, '۱۳': 13, '۱۴': 14, '۱۵': 15
}

districts = []
for feat in geojson_data["features"]:
    geom_type = feat.get("geometry", {}).get("type")
    props = feat.get("properties", {})
    name = props.get("name", "")
    admin_level = str(props.get("admin_level", ""))

    if geom_type not in ["Polygon", "MultiPolygon"] or admin_level != "9" or "خمینی" in name:
        continue

    d_num = None
    for p_num, val in persian_to_eng.items():
        if f"منطقه {p_num}" == name.strip() or f"منطقه {p_num} " in name:
            d_num = val
            break
    if d_num:
        poly = shape(feat["geometry"])
        districts.append({
            "id": f"D{d_num}",
            "d_num": d_num,
            "name": name,
            "lat": poly.centroid.y,
            "lon": poly.centroid.x,
            "geom": poly,
            "population": pop_dict[d_num]
        })

df_districts = pd.DataFrame(districts).sort_values("d_num").reset_index(drop=True)

In [8]:
refined_targets = np.load(r"Data\refined_targets.npy", allow_pickle=True)
target_counts = {d["id"]: 0 for d in districts}
for t in refined_targets:
    pt = Point(t["lon"], t["lat"])
    for d in districts:
        if d["geom"].contains(pt):
            target_counts[d["id"]] += 1
            break
refined_targets

array([{'id': 297227347, 'name': 'Badr Air Base', 'category': 'Aviation & Air Bases', 'type': 'airfield', 'lat': 32.6209518, 'lon': 51.6875522},
       {'id': 5643934331, 'name': 'Military/Defense Facility', 'category': 'Defense & Military', 'type': 'bunker', 'lat': 32.5659344, 'lon': 51.6541672},
       {'id': 6380568145, 'name': 'Military/Defense Facility', 'category': 'Defense & Military', 'type': 'checkpoint', 'lat': 32.5987561, 'lon': 51.6640166},
       {'id': 8495731262, 'name': 'بسیج', 'category': 'Defense & Military', 'type': 'complex', 'lat': 32.5529796, 'lon': 51.5019455},
       {'id': 8515927623, 'name': 'بسیج', 'category': 'Defense & Military', 'type': 'complex', 'lat': 32.6653343, 'lon': 51.5817841},
       {'id': 8515927624, 'name': 'بسیج', 'category': 'Defense & Military', 'type': 'complex', 'lat': 32.6653326, 'lon': 51.5817036},
       {'id': 8722031272, 'name': 'پایگاه هوایی هشتم شکاری', 'category': 'Aviation & Air Bases', 'type': 'airfield', 'lat': 32.7232001, 'lon': 51.8309047},
       {'id': 9801041398, 'name': 'شهرک صنعتی درچه', 'category': 'Heavy Industrial Parks', 'type': 'complex', 'lat': 32.612475, 'lon': 51.5775382},
       {'id': 10698857307, 'name': 'شهرک صنعتی نیک اندیش', 'category': 'Heavy Industrial Parks', 'type': 'complex', 'lat': 32.6147975, 'lon': 51.7672992},
       {'id': 10727464018, 'name': 'بسیج', 'category': 'Defense & Military', 'type': 'complex', 'lat': 32.6470338, 'lon': 51.6654663},
       {'id': 10734243500, 'name': 'شهرک صنعتی اسپادانا', 'category': 'Heavy Industrial Parks', 'type': 'complex', 'lat': 32.7348653, 'lon': 51.7560577},
       {'id': 10924126850, 'name': 'بسیج', 'category': 'Defense & Military', 'type': 'complex', 'lat': 32.7164912, 'lon': 51.5959575},
       {'id': 10926079961, 'name': 'بسیج', 'category': 'Defense & Military', 'type': 'complex', 'lat': 32.7160687, 'lon': 51.595979},
       {'id': 10981307257, 'name': 'بسیج', 'category': 'Defense & Military', 'type': 'complex', 'lat': 32.6478864, 'lon': 51.6654232},
       {'id': 12175531248, 'name': 'Military/Defense Facility', 'category': 'Defense & Military', 'type': 'bunker', 'lat': 32.7902321, 'lon': 51.9119441},
       {'id': 12175531249, 'name': 'Military/Defense Facility', 'category': 'Defense & Military', 'type': 'bunker', 'lat': 32.7908071, 'lon': 51.9118038},
       {'id': 12175531250, 'name': 'Military/Defense Facility', 'category': 'Defense & Military', 'type': 'bunker', 'lat': 32.7913968, 'lon': 51.9116635},
       {'id': 12175531251, 'name': 'Military/Defense Facility', 'category': 'Defense & Military', 'type': 'bunker', 'lat': 32.7897308, 'lon': 51.9106931},
       {'id': 12175531252, 'name': 'Military/Defense Facility', 'category': 'Defense & Military', 'type': 'bunker', 'lat': 32.790296, 'lon': 51.9105703},
       {'id': 12175531253, 'name': 'Military/Defense Facility', 'category': 'Defense & Military', 'type': 'bunker', 'lat': 32.7908611, 'lon': 51.9104183},
       {'id': 12175531254, 'name': 'Military/Defense Facility', 'category': 'Defense & Military', 'type': 'bunker', 'lat': 32.7901289, 'lon': 51.9098863},
       {'id': 12175531255, 'name': 'Military/Defense Facility', 'category': 'Defense & Military', 'type': 'bunker', 'lat': 32.7919226, 'lon': 51.9128443},
       {'id': 12175531256, 'name': 'Military/Defense Facility', 'category': 'Defense & Military', 'type': 'bunker', 'lat': 32.7913231, 'lon': 51.9130139},
       {'id': 12175531257, 'name': 'Military/Defense Facility', 'category': 'Defense & Military', 'type': 'bunker', 'lat': 32.7907481, 'lon': 51.9131542},
       {'id': 12175531258, 'name': 'Military/Defense Facility', 'category': 'Defense & Military', 'type': 'bunker', 'lat': 32.791844, 'lon': 51.914224},
       {'id': 12175531259, 'name': 'Military/Defense Facility', 'category': 'Defense & Military', 'type': 'bunker', 'lat': 32.7912838, 'lon': 51.914411},
       {'id': 12175531260, 'name': 'Military/Defense Facility', 'category': 'Defense & Military', 'type': 'bunker', 'lat': 32.7907088, 'lon': 51.9145572},
       {'id': 12175531261, 'name': 'Military/Defense Facility', 'category': 'Defense & Military', 'type': 'bunker', 'lat': 32.7924878, 'lon': 51.9127274},
       {'id': 12175531262, 'name': 'Military/Defense Facility', 'category': 'Defense & Military', 'type': 'bunker', 'lat': 32.7930628, 'lon': 51.9125637},
       {'id': 12175531263, 'name': 'Military/Defense Facility', 'category': 'Defense & Military', 'type': 'bunker', 'lat': 32.7930038, 'lon': 51.9139784},
       {'id': 12175531264, 'name': 'Military/Defense Facility', 'category': 'Defense & Military', 'type': 'bunker', 'lat': 32.7935689, 'lon': 51.9138148},
       {'id': 12175531265, 'name': 'Military/Defense Facility', 'category': 'Defense & Military', 'type': 'bunker', 'lat': 32.7941144, 'lon': 51.9136569},
       {'id': 12175531266, 'name': 'Military/Defense Facility', 'category': 'Defense & Military', 'type': 'bunker', 'lat': 32.7936475, 'lon': 51.9110555},
       {'id': 12175531267, 'name': 'Military/Defense Facility', 'category': 'Defense & Military', 'type': 'bunker', 'lat': 32.794193, 'lon': 51.9109035},
       {'id': 12175531268, 'name': 'Military/Defense Facility', 'category': 'Defense & Military', 'type': 'bunker', 'lat': 32.7937213, 'lon': 51.9096817},
       {'id': 12175531269, 'name': 'Military/Defense Facility', 'category': 'Defense & Military', 'type': 'bunker', 'lat': 32.7931414, 'lon': 51.9098571},
       {'id': 12175531270, 'name': 'Military/Defense Facility', 'category': 'Defense & Military', 'type': 'bunker', 'lat': 32.7925762, 'lon': 51.9100091},
       {'id': 12175531271, 'name': 'Military/Defense Facility', 'category': 'Defense & Military', 'type': 'bunker', 'lat': 32.7919865, 'lon': 51.9101319},
       {'id': 12175531272, 'name': 'Military/Defense Facility', 'category': 'Defense & Military', 'type': 'bunker', 'lat': 32.7919816, 'lon': 51.9093719},
       {'id': 12175531273, 'name': 'Military/Defense Facility', 'category': 'Defense & Military', 'type': 'bunker', 'lat': 32.7925762, 'lon': 51.9092082},
       {'id': 12175531274, 'name': 'Military/Defense Facility', 'category': 'Defense & Military', 'type': 'bunker', 'lat': 32.7931463, 'lon': 51.9090738},
       {'id': 12175531275, 'name': 'Military/Defense Facility', 'category': 'Defense & Military', 'type': 'bunker', 'lat': 32.7937655, 'lon': 51.9089276},
       {'id': 12175531276, 'name': 'Military/Defense Facility', 'category': 'Defense & Military', 'type': 'bunker', 'lat': 32.7911413, 'lon': 51.9171469},
       {'id': 12175531277, 'name': 'Military/Defense Facility', 'category': 'Defense & Military', 'type': 'bunker', 'lat': 32.7917605, 'lon': 51.9169891},
       {'id': 12175531278, 'name': 'Military/Defense Facility', 'category': 'Defense & Military', 'type': 'bunker', 'lat': 32.79064, 'lon': 51.9159193},
       {'id': 12175531279, 'name': 'Military/Defense Facility', 'category': 'Defense & Military', 'type': 'bunker', 'lat': 32.7923797, 'lon': 51.9154165},
       {'id': 12175531280, 'name': 'Military/Defense Facility', 'category': 'Defense & Military', 'type': 'bunker', 'lat': 32.792419, 'lon': 51.9140837},
       {'id': 12175531281, 'name': 'Military/Defense Facility', 'category': 'Defense & Military', 'type': 'bunker', 'lat': 32.7912324, 'lon': 51.915774},
       {'id': 12175531282, 'name': 'Military/Defense Facility', 'category': 'Defense & Military', 'type': 'bunker', 'lat': 32.7917991, 'lon': 51.9156578},
       {'id': 12175531283, 'name': 'Military/Defense Facility', 'category': 'Defense & Military', 'type': 'bunker', 'lat': 32.7923406, 'lon': 51.9168532},
       {'id': 12175531284, 'name': 'Military/Defense Facility', 'category': 'Defense & Military', 'type': 'bunker', 'lat': 32.7928766, 'lon': 51.9166872},
       {'id': 12175531285, 'name': 'Military/Defense Facility', 'category': 'Defense & Military', 'type': 'bunker', 'lat': 32.7929629, 'lon': 51.9153322},
       {'id': 12175531286, 'name': 'Military/Defense Facility', 'category': 'Defense & Military', 'type': 'bunker', 'lat': 32.7935431, 'lon': 51.91518},
       {'id': 12175531287, 'name': 'Military/Defense Facility', 'category': 'Defense & Military', 'type': 'bunker', 'lat': 32.7941062, 'lon': 51.9150023},
       {'id': 12175531288, 'name': 'Military/Defense Facility', 'category': 'Defense & Military', 'type': 'bunker', 'lat': 32.7934364, 'lon': 51.916535},
       {'id': 12175531289, 'name': 'Military/Defense Facility', 'category': 'Defense & Military', 'type': 'bunker', 'lat': 32.7940337, 'lon': 51.9164284},
       {'id': 12175531290, 'name': 'Military/Defense Facility', 'category': 'Defense & Military', 'type': 'bunker', 'lat': 32.7946224, 'lon': 51.9162609},
       {'id': 12175531291, 'name': 'Military/Defense Facility', 'category': 'Defense & Military', 'type': 'bunker', 'lat': 32.7951898, 'lon': 51.9161341},
       {'id': 12175531292, 'name': 'Military/Defense Facility', 'category': 'Defense & Military', 'type': 'bunker', 'lat': 32.7946608, 'lon': 51.9149211},
       {'id': 12175531293, 'name': 'Military/Defense Facility', 'category': 'Defense & Military', 'type': 'bunker', 'lat': 32.7901165, 'lon': 51.9133001},
       {'id': 12175531294, 'name': 'Military/Defense Facility', 'category': 'Defense & Military', 'type': 'bunker', 'lat': 32.7909577, 'lon': 51.9096637},
       {'id': 12175596355, 'name': 'Military/Defense Facility', 'category': 'Defense & Military', 'type': 'bunker', 'lat': 32.7879704, 'lon': 51.9109757},
       {'id': 12175596356, 'name': 'Military/Defense Facility', 'category': 'Defense & Military', 'type': 'bunker', 'lat': 32.787356, 'lon': 51.9111178},
       {'id': 12175596357, 'name': 'Military/Defense Facility', 'category': 'Defense & Military', 'type': 'bunker', 'lat': 32.7879533, 'lon': 51.9126911},
       {'id': 12175596358, 'name': 'Military/Defense Facility', 'category': 'Defense & Military', 'type': 'bunker', 'lat': 32.788508, 'lon': 51.9125439},
       {'id': 12175596359, 'name': 'Military/Defense Facility', 'category': 'Defense & Military', 'type': 'bunker', 'lat': 32.7884269, 'lon': 51.9139649},
       {'id': 12175596360, 'name': 'Military/Defense Facility', 'category': 'Defense & Military', 'type': 'bunker', 'lat': 32.7878552, 'lon': 51.9140867},
       {'id': 12175596417, 'name': 'Military/Defense Facility', 'category': 'Defense & Military', 'type': 'bunker', 'lat': 32.7946351, 'lon': 51.9135043},
       {'id': 12175596418, 'name': 'Military/Defense Facility', 'category': 'Defense & Military', 'type': 'bunker', 'lat': 32.7941375, 'lon': 51.9122624},
       {'id': 12175596419, 'name': 'Military/Defense Facility', 'category': 'Defense & Military', 'type': 'bunker', 'lat': 32.7935911, 'lon': 51.9123982},
       {'id': 12175596420, 'name': 'Military/Defense Facility', 'category': 'Defense & Military', 'type': 'bunker', 'lat': 32.7930528, 'lon': 51.9111951},
       {'id': 12175596421, 'name': 'Military/Defense Facility', 'category': 'Defense & Military', 'type': 'bunker', 'lat': 32.7924084, 'lon': 51.9113115},
       {'id': 12175596430, 'name': 'Military/Defense Facility', 'category': 'Defense & Military', 'type': 'bunker', 'lat': 32.7714993, 'lon': 51.9011931},
       {'id': 12175596431, 'name': 'Military/Defense Facility', 'category': 'Defense & Military', 'type': 'bunker', 'lat': 32.7708588, 'lon': 51.9013454},
       {'id': 27374098, 'name': 'Military/Defense Facility', 'category': 'Aviation & Air Bases', 'type': 'runway', 'lat': 32.5672588, 'lon': 51.691244},
       {'id': 134234971, 'name': 'Shahid Mohammad Montazeri Power Plant', 'category': 'Energy & Refining', 'type': 'plant', 'lat': 32.7973573, 'lon': 51.4970546},
       {'id': 136486105, 'name': 'Military/Defense Facility', 'category': 'Aviation & Air Bases', 'type': 'runway', 'lat': 32.5826803, 'lon': 52.0024422},
       {'id': 178242477, 'name': 'Isfahan Shahid Beheshti International Airport', 'category': 'Aviation & Air Bases', 'type': 'airfield', 'lat': 32.7627619, 'lon': 51.8740902},
       {'id': 194327162, 'name': 'شهرک صنعتی جی', 'category': 'Heavy Industrial Parks', 'type': 'complex', 'lat': 32.6712884, 'lon': 51.8476044},
       {'id': 194442523, 'name': 'Military/Defense Facility', 'category': 'Aviation & Air Bases', 'type': 'aerodrome', 'lat': 32.4822352, 'lon': 51.824458},
       {'id': 195696458, 'name': 'Military/Defense Facility', 'category': 'Defense & Military', 'type': 'complex', 'lat': 32.5787712, 'lon': 51.6558722},
       {'id': 195770241, 'name': 'Military/Defense Facility', 'category': 'Defense & Military', 'type': 'complex', 'lat': 32.5749875, 'lon': 51.6680211},
       {'id': 196702675, 'name': 'Esfahan Artillery Learning Centre', 'category': 'Defense & Military', 'type': 'complex', 'lat': 32.619393, 'lon': 51.6546644},
       {'id': 198444892, 'name': 'Bonyad Mostazafin', 'category': 'Defense & Military', 'type': 'complex', 'lat': 32.6408579, 'lon': 51.6602145},
       {'id': 345659311, 'name': 'هوانیروز', 'category': 'Defense & Military', 'type': 'complex', 'lat': 32.5968163, 'lon': 51.6763887},
       {'id': 345660986, 'name': 'حوزه مقاومت بسیج', 'category': 'Defense & Military', 'type': 'complex', 'lat': 32.5928356, 'lon': 51.6685283},
       {'id': 380363965, 'name': 'شهرک صنعتی منتظریه', 'category': 'Heavy Industrial Parks', 'type': 'complex', 'lat': 32.681829, 'lon': 51.4141549},
       {'id': 380363966, 'name': 'شهرک صنعتی کاوه', 'category': 'Heavy Industrial Parks', 'type': 'complex', 'lat': 32.6739238, 'lon': 51.4063373},
       {'id': 401107819, 'name': 'شهرک صنعتی سروش بادران', 'category': 'Heavy Industrial Parks', 'type': 'complex', 'lat': 32.5474538, 'lon': 51.8080106},
       {'id': 401116987, 'name': 'آموزشگاه شهید بهشتی نیروی انتظامی', 'category': 'Defense & Military', 'type': 'complex', 'lat': 32.5950354, 'lon': 51.7844708},
       {'id': 401116990, 'name': 'شهرک صنعتی مولانا', 'category': 'Heavy Industrial Parks', 'type': 'complex', 'lat': 32.5822787, 'lon': 51.7799916},
       {'id': 401117016, 'name': 'Military/Defense Facility', 'category': 'Defense & Military', 'type': 'complex', 'lat': 32.542026, 'lon': 51.6791139},
       {'id': 401117024, 'name': 'لشکر ۱۴ امام حسین (ع)', 'category': 'Defense & Military', 'type': 'complex', 'lat': 32.5042417, 'lon': 51.6911556},
       {'id': 437158139, 'name': 'Isfahan Power Plant', 'category': 'Energy & Refining', 'type': 'plant', 'lat': 32.6263874, 'lon': 51.5692305},
       {'id': 533956046, 'name': 'Military/Defense Facility', 'category': 'Aviation & Air Bases', 'type': 'runway', 'lat': 32.7488178, 'lon': 51.8618252},
       {'id': 533956048, 'name': 'Military/Defense Facility', 'category': 'Aviation & Air Bases', 'type': 'runway', 'lat': 32.7528766, 'lon': 51.8607876},
       {'id': 537533243, 'name': 'Mahmoudabad Industrial Town', 'category': 'Heavy Industrial Parks', 'type': 'complex', 'lat': 32.8019127, 'lon': 51.5546525},
       {'id': 540732662, 'name': 'شهرک صنعتی درچه', 'category': 'Heavy Industrial Parks', 'type': 'complex', 'lat': 32.6412014, 'lon': 51.5501827},
       {'id': 591216296, 'name': 'Military/Defense Facility', 'category': 'Defense & Military', 'type': 'range', 'lat': 32.5628866, 'lon': 51.6601677},
       {'id': 591216314, 'name': 'Military/Defense Facility', 'category': 'Defense & Military', 'type': 'range', 'lat': 32.5614534, 'lon': 51.6524215},
       {'id': 591216388, 'name': 'Military/Defense Facility', 'category': 'Defense & Military', 'type': 'complex', 'lat': 32.5644675, 'lon': 51.6647999},
       {'id': 591216395, 'name': 'Shahid Vatan Pour Air Base', 'category': 'Aviation & Air Bases', 'type': 'airfield', 'lat': 32.5701183, 'lon': 51.6882885},
       {'id': 591216412, 'name': 'Military/Defense Facility', 'category': 'Defense & Military', 'type': 'complex', 'lat': 32.5921756, 'lon': 51.6021408},
       {'id': 591216414, 'name': 'Military/Defense Facility', 'category': 'Defense & Military', 'type': 'complex', 'lat': 32.6024083, 'lon': 51.5926834},
       {'id': 591216422, 'name': 'Military/Defense Facility', 'category': 'Defense & Military', 'type': 'complex', 'lat': 32.5864834, 'lon': 51.6154354},
       {'id': 591216423, 'name': 'Military/Defense Facility', 'category': 'Defense & Military', 'type': 'complex', 'lat': 32.5812747, 'lon': 51.6121464},
       {'id': 591216424, 'name': 'Military/Defense Facility', 'category': 'Defense & Military', 'type': 'complex', 'lat': 32.5765499, 'lon': 51.6243183},
       {'id': 591216425, 'name': 'Military/Defense Facility', 'category': 'Defense & Military', 'type': 'complex', 'lat': 32.5869342, 'lon': 51.6296282},
       {'id': 591216426, 'name': 'Military/Defense Facility', 'category': 'Defense & Military', 'type': 'complex', 'lat': 32.5821874, 'lon': 51.6338881},
       {'id': 591216428, 'name': 'Military/Defense Facility', 'category': 'Defense & Military', 'type': 'complex', 'lat': 32.5805402, 'lon': 51.6094518},
       {'id': 591216430, 'name': 'Military/Defense Facility', 'category': 'Defense & Military', 'type': 'training_area', 'lat': 32.6005075, 'lon': 51.6250004},
       {'id': 591216431, 'name': 'Military/Defense Facility', 'category': 'Defense & Military', 'type': 'training_area', 'lat': 32.5977402, 'lon': 51.6219209},
       {'id': 591216432, 'name': 'Military/Defense Facility', 'category': 'Defense & Military', 'type': 'training_area', 'lat': 32.597295, 'lon': 51.6189226},
       {'id': 591216433, 'name': 'Military/Defense Facility', 'category': 'Defense & Military', 'type': 'training_area', 'lat': 32.5974731, 'lon': 51.6170139},
       {'id': 591216434, 'name': 'Military/Defense Facility', 'category': 'Defense & Military', 'type': 'training_area', 'lat': 32.5950917, 'lon': 51.6142995},
       {'id': 591216435, 'name': 'Military/Defense Facility', 'category': 'Defense & Military', 'type': 'training_area', 'lat': 32.5938119, 'lon': 51.6120144},
       {'id': 591216436, 'name': 'Military/Defense Facility', 'category': 'Defense & Military', 'type': 'training_area', 'lat': 32.6009728, 'lon': 51.6272507},
       {'id': 591216449, 'name': 'Military/Defense Facility', 'category': 'Defense & Military', 'type': 'complex', 'lat': 32.5966916, 'lon': 51.6123103},
       {'id': 591216455, 'name': 'Military/Defense Facility', 'category': 'Defense & Military', 'type': 'range', 'lat': 32.5812949, 'lon': 51.6235868},
       {'id': 591216461, 'name': 'Military/Defense Facility', 'category': 'Defense & Military', 'type': 'complex', 'lat': 32.5535881, 'lon': 51.6010798},
       {'id': 668467628, 'name': 'Military/Defense Facility', 'category': 'Aviation & Air Bases', 'type': 'runway', 'lat': 32.621128, 'lon': 51.6968612},
       {'id': 668473423, 'name': 'Military/Defense Facility', 'category': 'Aviation & Air Bases', 'type': 'runway', 'lat': 32.4852871, 'lon': 51.8263576},
       {'id': 677572781, 'name': 'پادگان ۱۰۱ انبیا', 'category': 'Defense & Military', 'type': 'complex', 'lat': 32.6913708, 'lon': 51.4362117},
       {'id': 691375045, 'name': 'بسیج محلی', 'category': 'Defense & Military', 'type': 'office', 'lat': 32.5426134, 'lon': 51.4919206},
       {'id': 798247061, 'name': 'شهرک صنعتی ده سرخ', 'category': 'Heavy Industrial Parks', 'type': 'complex', 'lat': 32.4032147, 'lon': 51.6979017},
       {'id': 864225915, 'name': 'صنایع دانش بنیان امام حسین (ع) سپاه پاسداران', 'category': 'Defense & Military', 'type': 'training_area', 'lat': 32.7094532, 'lon': 51.4922105},
       {'id': 864227894, 'name': 'سپاه خمینی شهر', 'category': 'Defense & Military', 'type': 'complex', 'lat': 32.7030865, 'lon': 51.5043944},
       {'id': 876119494, 'name': 'Military/Defense Facility', 'category': 'Defense & Military', 'type': 'complex', 'lat': 32.7792332, 'lon': 51.6254559},
       {'id': 882942202, 'name': 'پادگان ۱۵ خرداد', 'category': 'Defense & Military', 'type': 'complex', 'lat': 32.4539295, 'lon': 51.7404608},
       {'id': 929596894, 'name': 'فرماندهی نیرو انتظامی استان اصفهان', 'category': 'Defense & Military', 'type': 'range', 'lat': 32.5441284, 'lon': 51.6899707},

In [3]:
x = Variable(
    container=m,
    name="x",
    domain=[i, j],
    type="Positive",
    description="amount of commodity to ship from plant i to market j",
)

In [4]:
supply = Equation(
    container=m, name="supply", domain=i, description="observe supply limit at plant i"
)
demand = Equation(
    container=m, name="demand", domain=j, description="satisfy demand at market j"
)

In [6]:
supply[i] = Sum(j, x[i, j]) <= a[i]
demand[j] = Sum(i, x[i, j]) >= b[j]

In [7]:
print(demand.latexRepr())

$
\sum_{i} x_{i,j} \geq b_{j}\hfill \forall j
$

In [8]:
obj = Sum((i, j), c[i, j] * x[i, j])

In [9]:
transport = Model(
    m,
    name="transport",
    equations=[supply, demand],
    problem="LP",
    sense=Sense.MIN,
    objective=obj,
)

In [10]:
transport = Model(
    m,
    name="transport",
    equations=m.getEquations(),
    problem="LP",
    sense=Sense.MIN,
    objective=obj,
)

In [11]:
i.setRecords(['seattle', 'san-diego'])
j.setRecords(['new-york', 'chicago', 'topeka'])
a.setRecords([("seattle", 350), ("san-diego", 600)])
b.setRecords([("new-york", 325), ("chicago", 300), ("topeka", 275)])
i.records

         uni element_text
0    seattle
1  san-diego

In [12]:
import pandas as pd

distances = pd.DataFrame(
    [
        ["seattle", "new-york", 2.5],
        ["seattle", "chicago", 1.7],
        ["seattle", "topeka", 1.8],
        ["san-diego", "new-york", 2.5],
        ["san-diego", "chicago", 1.8],
        ["san-diego", "topeka", 1.4],
    ],
    columns=["from", "to", "distance"]
).set_index(["from", "to"])
d = Parameter(
    container=m,
    name="d",
    domain=[i, j],
    description="distance between plant i and market j",
    records=distances.reset_index(),
)
d.records

        from        to  value
0    seattle  new-york    2.5
1    seattle   chicago    1.7
2    seattle    topeka    1.8
3  san-diego  new-york    2.5
4  san-diego   chicago    1.8
5  san-diego    topeka    1.4

In [13]:
freight_cost = 90
cost = freight_cost * distances / 1000
c.setRecords(cost.reset_index())
c.records

        from        to  value
0    seattle  new-york  0.225
1    seattle   chicago  0.153
2    seattle    topeka  0.162
3  san-diego  new-york  0.225
4  san-diego   chicago  0.162
5  san-diego    topeka  0.126

In [14]:
c[i, j] = freight_cost * d[i, j] / 1000
c.records

           i         j  value
0    seattle  new-york  0.225
1    seattle   chicago  0.153
2    seattle    topeka  0.162
3  san-diego  new-york  0.225
4  san-diego   chicago  0.162
5  san-diego    topeka  0.126

In [15]:
import sys

transport.solve(output=sys.stdout)

--- Job _VPwtUnkdSV_pjGlT7iC_Kw.gms Start 09/16/26 19:10:48 54.4.0 9a60ae27 WEX-WEI x86 64bit/MS Windows
--- Applying:
    C:\Users\shaya\Desktop\GAMS\.gamspy_venv\Lib\site-packages\gamspy_base\gmsprmNT.txt
--- GAMS Parameters defined
    LP cplex
    Input C:\Users\shaya\AppData\Local\Temp\tmpcbdqqui6\_VPwtUnkdSV_pjGlT7iC_Kw.gms
    Output C:\Users\shaya\AppData\Local\Temp\tmpcbdqqui6\_VPwtUnkdSV_pjGlT7iC_Kw.lst
    ScrDir C:\Users\shaya\AppData\Local\Temp\tmpcbdqqui6\tmpyo8m3mvc\
    SysDir C:\Users\shaya\Desktop\GAMS\.gamspy_venv\Lib\site-packages\gamspy_base\
    LogOption 3
    License C:\Users\shaya\Desktop\GAMS\.gamspy_venv\Lib\site-packages\gamspy_base\gamslice.txt
    OptFile 0
    OptDir C:\Users\shaya\AppData\Local\Temp\tmpcbdqqui6\
    LimRow 0
    LimCol 0
    GDX C:\Users\shaya\AppData\Local\Temp\tmpcbdqqui6\_VPwtUnkdSV_pjGlT7iC_Kwout.gdx
    SolPrint 0
    SolveLink 2
    PreviousWork 1
    gdxSymbols newOrChangedNoData
System information: 4 physical cores and 8 Gb physical memory detected
--- Starting compilation
--- _VPwtUnkdSV_pjGlT7iC_Kw.gms(63) 4 Mb
--- Starting execution: elapsed 0:00:00.020
--- _VPwtUnkdSV_pjGlT7iC_Kw.gms(207) 4 Mb
--- Generating LP model transport
--- _VPwtUnkdSV_pjGlT7iC_Kw.gms(208) 4 Mb
---   6 rows  7 columns  19 non-zeroes
--- Range statistics (absolute non-zero finite values)
--- RHS       [min, max] : [ 2.750E+02, 6.000E+02] - Zero values observed as well
--- Bound     [min, max] : [        NA,        NA] - Zero values observed as well
--- Matrix    [min, max] : [ 1.260E-01, 1.000E+00]
--- Executing CPLEX (Solvelink=2): elapsed 0:00:00.213

IBM ILOG CPLEX   54.4.0 9a60ae27 Sep 9, 2026           WEI x86 64bit/MS Window

*** This solver runs with a demo license. No commercial use.
--- GMO setup time: 0.00s
--- GMO memory 0.50 Mb (peak 0.50 Mb)
--- Dictionary memory 0.00 Mb
--- Cplex 22.1.2.0 link memory 0.00 Mb (peak 0.00 Mb)
--- Starting Cplex

Version identifier: 22.1.2.0 | 2024-11-25 | 0edbb82fd
CPXPARAM_Advance                                 0
CPXPARAM_Simplex_Display                         2
CPXPARAM_MIP_Display                             4
CPXPARAM_MIP_Pool_Capacity                       0
CPXPARAM_Preprocessing_QCPDuals                  0
CPXPARAM_MIP_Tolerances_AbsMIPGap                0
Tried aggregator 1 time.
LP Presolve eliminated 0 rows and 1 columns.
Reduced LP has 5 rows, 6 columns, and 12 nonzeros.
Presolve time = 0.00 sec. (0.00 ticks)

Iteration      Dual Objective            In Variable           Out Variable
     1              73.125000    x(seattle,new-york) demand(new-york) slack
     2             119.025000     x(seattle,chicago)  demand(chicago) slack
     3             153.675000    x(san-diego,topeka)   demand(topeka) slack
     4             153.675000  x(san-diego,new-york)  supply(seattle) slack

--- LP status (1): optimal.
--- Cplex Time: 0.00sec (det. 0.01 ticks)


Optimal solution found
Objective:          153.675000

--- Reading solution for model transport
--- Executing after solve: elapsed 0:00:00.758
--- _VPwtUnkdSV_pjGlT7iC_Kw.gms(211) 4 Mb
--- _VPwtUnkdSV_pjGlT7iC_Kw.gms(241) 4 Mb
--- GDX File (execute_unload) C:\Users\shaya\AppData\Local\Temp\tmpcbdqqui6\_MlLCj6oCSy_YIrQw3XRcVg.gdx
--- GDX File C:\Users\shaya\AppData\Local\Temp\tmpcbdqqui6\_VPwtUnkdSV_pjGlT7iC_Kwout.gdx
*** Status: Normal completion
--- Job _VPwtUnkdSV_pjGlT7iC_Kw.gms Stop 09/16/26 19:10:48 elapsed 0:00:00.763

,Solver Status,Model Status,Objective,Num of Equations,Num of Variables,Model Type,Solver,Solver Time
0,NormalCompletion,OptimalGlobal,153.675,6.0,7.0,LP,CPLEX,0.538